### ISSUE TITLE
Tracking the followups 

### ISSUE THREAD

**Issue by gmkumar2005** [softwaremill/codebrag#21]
As an admin 
  I should be able to see progress of code reviews done by the team
In order to 
 Evaluate if code reviews are practiced regularly. 

Suggested approach is to add a tab for 'ALL followups' which displays all the reviews which are open.
This view will be visible only of the admin. Admin user can see all the followups and discussion in this view. 
![image](https://cloud.githubusercontent.com/assets/1712742/5556431/47f89b0a-8d01-11e4-9338-9ae259e9a27c.png)

**Comment by Zuchos** [comment]
Codebrag's flow doesn't define such role as Admin or Supervisor.
