### ISSUE TITLE
How does StatisticEventsCollector work

### ISSUE THREAD

**Issue by gmkumar2005** [softwaremill/codebrag#24]
I am trying to display weekly statistics similar to the one below. However the events table does not get updated when there is an activity. Is it dependent on send-anon-usage-data = false ?
How is the events table updated ?

![image](https://cloud.githubusercontent.com/assets/1712742/5791752/c0d9b310-9f12-11e4-862f-6fa531276a30.png)

**Comment by mostr** [comment]
There is nothing in the code that prevents events from being persisted even if sending stats is disabled, so I can't really help much here. One thing, we are only persisting `StatisticEvent` subclasses. Do you have hard time storing existing event types, or you made up your own?

**Comment by gmkumar2005** [comment]
Issue is resolved. In dev environment the events were not populating. In production they get updated instantly. @mostr I am not using any custom event.  There are four events being captured
 1. Comment Added
 2. Like Added
 3. UserRegistered
 4. Commit Reviewed

Additionally I want display CommitsAdded (commits count)  also. Please advice  the best way get this count. RepositoryCache seems to be an option. Another could be add a StatisticEvent of type Commit. 
Is there any reason for not adding Commit as an event ?
 
Below is the sample weekly statistics chart 
![image](https://cloud.githubusercontent.com/assets/1712742/5832432/290438de-a16b-11e4-8322-4a7f19b62f36.png)

**Comment by mostr** [comment]
What would `Commit` event mean? Do you want to track how many new commits were pulled by Codebrag with each repo update? If so I'd suggest to hook in [here](https://github.com/softwaremill/codebrag/blob/master/codebrag-service/src/main/scala/com/softwaremill/codebrag/service/commits/CommitImportService.scala#L21) and make use of this `MultibranchLoadCommitResult`. Here you get all new commits for all branches in given repository. You can now publish an event with calculated counts. Hope this helps.
