### ISSUE TITLE
Cannot pull into a repository with state: MERGING

### ISSUE THREAD

**Issue by schrepfler** [softwaremill/codebrag#25]
Just noticed this exception in the logs, what does it mean? If this is expected perhaps it should be mentioned on the docs.
15:19:48.403 [codebrag-akka.actor.default-dispatcher-4] ERROR c.s.c.s.commits.CommitImportService - Cannot pull changes from upstream
org.eclipse.jgit.api.errors.WrongRepositoryStateException: Cannot pull into a repository with state: MERGING

**Comment by mostr** [comment]
Looks like someone was messing up with repository copy that codebrag uses. You could probably go to that repo, reset it with `--hard`, pull changes to be in sync and Codebrag should be fine after that. Just do it on Codebrag turned off, just in case.

**Comment by mostr** [comment]
Hey @schrepfler, any success with that? Would like to either close this one or investigate it further if possible.

**Comment by schrepfler** [comment]
Yup, I think it got solved because of that but I can't replicate again as I've reset the db :(

**Comment by mostr** [comment]
No worries. Closing this one, but feel free to reopen if it pops up again.
