### ISSUE TITLE
API to know number of commits waiting for review

### ISSUE THREAD

**Issue by kenji21** [softwaremill/codebrag#26]
We have an eXtreme Feedback Panel showing build failed / unstable. Basic idea is to have a simple script that will curl the codebrag API to check if there are too many commits waiting for review.
If more than N commits -> build unstable, and more than M -> build failed \o/

It may be related to another API : https://github.com/softwaremill/codebrag/issues/3

**Comment by tjordanchat** [comment]
That is impossible to do with codebrag. Codebrag can ONLY be used from the GUI and not by a rest interface because the rest interface is proprietary.

**Comment by mostr** [comment]
@tjordanchat although Codebrag has JSON-based API, it's only used for UI purposes and doesn't really have all the features available for standalone clients. It also doesn't support authentication other than cookie-based (like in browsers) as for now. 
Any request done by browser can be done by standalone clients but keep in mind the only authentication available is user/password and cookie-based method. I guess it's not proprietary, it's just not suited for standalone clients. But hey, it's open source, feel free to contribute :)
