### ISSUE TITLE
Assign a team member to review a commit?

### ISSUE THREAD

**Issue by machinelady** [softwaremill/codebrag#29]
We just started using Codebrag at our company, and we'd like to have a way to assign a specific team member to review a commit so it shows up in their "to review" queue. This could be done by either an admin or by the committer themselves. 
I couldn't find a way to do this in  Codebrag 2.3.1, but it would be great if there was!

**Comment by spoganshev** [comment]
Yes. It would be perfect if Codebrag analysed commit message for patterns like "Reviewers: user1,user2"

**Comment by mostr** [comment]
In Codebrag there is no way to "assign" commits to given reviewers. It's more like everyone can review everyting. The only option that is pretty-close to what you need is "reviewers_count" in config file. It basically means that when at least required number of people reviewed given commit, it will not be shown on your list. Also in the commit view (top right corner) you can see whether the commit was already reviewed (and who did it already if so) or not.

For now we don't have plans introducing the feature you request, sorry.

**Comment by lukaszlenart** [comment]
Yeah... but we accept PRs :)

**Comment by machinelady** [comment]
Okay, we'll just have to find a workaround, then - and when someone here finds the time to implement the feature, they'll probably be happy to submit a PR ;) Thanks, anyway!
