### ISSUE TITLE
Ability to review a bunch of commits in order to integrate better with issue tracker

### ISSUE THREAD

**Issue by kakawait** [softwaremill/codebrag#30]
Inside my project architecture we are using git + issue tracker. Thus per feature/bug/enhance we create a ticket on our issue tracker and then review the issue (and not per commit).

Issue can contains 1 or more commit and I wanted to know if it's possible to create a single review for a bunch of commit representing a ticket?

**It would be good to have a single view for this bunch of commit**.

**Comment by Zuchos** [comment]
Right now it's not possible.
