### ISSUE TITLE
Initial SVN clone depth

### ISSUE THREAD

**Issue by grrussel** [softwaremill/codebrag#38]
The https://github.com/softwaremill/codebrag/wiki/Installation#step-1-clone-your-repository guide wants the git svn clone operation to pull down the entire (lengthy!) history of the SVN repo

Is that necessary? Can a shallower clone be performed? 

We will not, as a rule, be performing code reviews of code of historic interest only.

**Comment by grrussel** [comment]
It seems that a shallower clone does indeed work fine, and perhaps should be the default suggestion?

**Comment by bandrzejczak** [comment]
You can perform a shallow clone by using `--revision=HEAD` parameter of `git svn clone` command.

Please find more information on `git svn clone` in the docs: http://git-scm.com/docs/git-svn

**Comment by bandrzejczak** [comment]
I've added appropriate information in the docs.
