### ISSUE TITLE
Review branch diff instead of atomic commits

### ISSUE THREAD

**Issue by glepretre** [softwaremill/codebrag#52]
Hi,

Our team is starting to use codebrag (but not code reviews, we are used to it now) and we were wondering if it would be possible to review a full branch diff because we are strictly working with git branches for each fix/feat.

Reviewing each commit can help understanding all the way of thinking through time and code but sometimes one experiment does not remain at the end of the implementation or has completely changed. :grin: 

EDIT: What I'm thinking of is [the GitHub Pull Request files view](https://github.com/softwaremill/codebrag/pull/10/files)

**Comment by Ghalko** [comment]
:+1:

**Comment by alourie** [comment]
:+1:
