### ISSUE TITLE
Comment multiple lines

### ISSUE THREAD

**Issue by glepretre** [softwaremill/codebrag#53]
Hi,

Are you planning to allow to commenting multiple lines at once (code block)?

I have not yet read enough of your source code but I can imagine that would require structural changes and/or refactoring.

Thank you :wink:

**Comment by mostr** [comment]
Yeah, it's really complicated thing. Not sure if we're gonna work on it (definitely not in the nearest future), but you know, PR's are welcome ;)
Also I'm not sure how it should work, e.g. you comment on lines 10-20 and the other person would like to comment on lines 13-15. How would you display/manage these two discussion threads? What if someone then wants to comment lines 14-25?
