### ISSUE TITLE
display commits from the newest one

### ISSUE THREAD

**Issue by bartoslaw** [softwaremill/codebrag#63]
hey, first for all thank you for great piece of software :)

we really like using it, but recently our coders started complaining (especially when cloning new, but pretty old repo) that they see commits from ~2months ago, and there's no possibility to fast forward to the new ones.

It's still important to also review older code, but is there some way, or are you planning to add possibility to filter commits/limit only to newest or smthg?

thanks
Bart

**Comment by mikehoague** [comment]
This feature would be very helpful to me as well

**Comment by jeffjensen** [comment]
Yes, agreed.  Some type of "starting commit" or "next commit to review" option per person.
Or a review paging feature to skip to most recent commit.
Currently can't "next" to see newer commits as it stops showing new after a couple of pages.

On previous project when using CodeBrag, new people to the project (and existing when "behind on reviews") would skip doing code reviews/using CodeBrag.  We reduced the number of reviewers needed to mark it as reviewed as a work around to clear the older ones faster (not ideal).
