### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by tolhan** [softwaremill/codebrag#66]
Hi codebrag developers, 

I am evaluating some review tools, and codebrag is my favorite tool. I like it because of its easy installation and configuration, and especially easy adding new repositories, really I love it. Other tools are oversized and very slow. 

But to be short, we need some features that are necessary for us...:
- **Blacklist**, ability to ignore filetypes, files and folders.
- Report function(something like statistics and review coverage: filex , reviewed by x, revision z, date) and the ability to **export it (!)** to files
- **Search function** with filters like looking for comments from person X on project Y file Z Branch b

Thank you in advance, I hope to hear from you.

**Comment by mostr** [comment]
We don't plan such features in near future, sorry. But feel free to contribute if you come up with these features implemented at some point.
