### ISSUE TITLE
The "How Codebrag works" video in the wiki no longer exists

### ISSUE THREAD

**Issue by markrian** [softwaremill/codebrag#75]
In this [wiki page](https://github.com/softwaremill/codebrag/wiki/How-Codebrag-Works), which is linked to within codebrag via its "Learn more" buttons, the video linked no longer exists. I can't seem to find that video via any search engines, either. Can this video be made available again, or that link/wiki be updated?

**Comment by lukaszlenart** [comment]
Done! I have restored all the videos we had and put them on my channel, you can view them all here https://www.youtube.com/channel/UC00eMjutHznUdGrGiIDhDAw
