### ISSUE TITLE
Running run.bat creates OverlappingFileLockException

### ISSUE THREAD

**Issue by Jeyatharsini24** [softwaremill/codebrag#85]
Hi, I cloned the codebrag repo to my local machine and try to run run.bat. It creates OverlappingFileLockException.

I have installed Scala 2.11.8.400,
Nodejs 0.10.13,
sbt 0.13.11.2

I have set path for npm and node in environmental variables.
What did I miss here?

How to resolve it?

When I googled it I found that to append lock:false to boot properties. I did so also.. Nothing happened. What should I do?

**Comment by lukaszlenart** [comment]
But you want to start CBR or start developing some new features?

**Comment by Jeyatharsini24** [comment]
I want to start CBR..

**Comment by lukaszlenart** [comment]
So the simplest way is to download distro from here http://codebrag.com/

**Comment by Jeyatharsini24** [comment]
I removed .ivy2 and .sbt folders. Now it's fine
