### ISSUE TITLE
Live demo please!

### ISSUE THREAD

**Issue by fresheneesz** [softwaremill/codebrag#9]
Comparing the couple good code review options out there would be much easier if you guys had a live demo too!

**Comment by surrehman76** [comment]
Can we document somewhere how does it really work i.e. I failed to find any reviews when I did git push origin master from one of repos managed by Codebrag, what is the magic push to initiate code reviews

**Comment by mostr** [comment]
In fact there is nothing magical there. You push commits to repo and your colleagues (who watch this repo in Codebrag) are given these commits on their "to review" list. They can either mark it as reviewed without any other action, or comment/like some piece of your work. And that's basically all. Codebrag doesn't have any strict "review flow".

**Comment by surrehman76** [comment]
ok thanks that is cool, bit off the topic but I seem to be able t clone by public repo from github into codebrag repos and ssh works fine but when I push any changes to it they do not seem to appear in review list and log file shows 12:57:02.417 [codebrag-akka.actor.default-dispatcher-4] ERROR c.s.c.repository.GitRepository - Cannot pull changes for repo /home/xx/Codebrag/codebrag-2.3.1/repos/xx because of: git@github.com:sxxxxx.git: USERAUTH fail
12:57:02.418 [codebrag-akka.actor.default-dispatcher-4] ERROR c.s.c.s.commits.CommitImportService - Cannot pull changes from upstream

**Comment by mostr** [comment]
Looks like you need to provide proper auth configuration. Take a look at `codebrag.conf` file and fill in repository settings (either user/pass or passphrase to your ssh keystore).

**Comment by surrehman76** [comment]
wiered as I add both and useranme/password and passhphrase but does not work. On the file system where Codebrag is installed I am able to clone the repo with same credentials i.e. ssh key as in codebag.conf Not sure what its doing at port 22 of github:
Cannot pull changes from upstream
org.eclipse.jgit.errors.UnsupportedCredentialItem: ssh://git@github.com:22: org.eclipse.jgit.transport.CredentialItem$StringType:Passphrase for

**Comment by mostr** [comment]
Looks like you use ssh with key, so you probably have passphrase. If so in `codebrag.conf` uncomment __ONLY__ `passphrase` and set it to correct value. We use it on daily basis and it works fine for us.

**Comment by VijayKrishn** [comment]
Hi, we are planning to use codebrag as our review tool. I have a doubt about configuration. How can I push the changes to codebrag repo instead of origin master which is on bitbucket for the review? Can you post any sample configuration and what would be the remote URL to push the changes onto codebrag repo.
Thank you

**Comment by gmkumar2005** [comment]
Vijay codebrag is a post commit review tool. 
It will allow review of the code which is already committed. It will pull all the changes from your repo and display the diff for review 

Kiran

**Comment by gmkumar2005** [comment]
Vijaya please follow the instructions in the installation guide. https://github.com/softwaremill/codebrag/wiki/Installation.
It will automatically sync origin master. no need of any additional config.

**Comment by VijayKrishn** [comment]
One last question Kumar. Is it possible to checkin on top of a reviewed code instead of a new commit? After we address the reviewed comments, if I change the code addressing the comments, how can I commit on top of it?

**Comment by gmkumar2005** [comment]
It is just another commit. It will be part of a new change set. The new change set undergoes the same review cycle as any other commit. 

Kiran

**Comment by VijayKrishn** [comment]
Hi Kiran
How often does the codebrag pull in the new changes from the repo (On the website it just states that it pulls in periodically, can we modify the period)? How does it read from where to pull in the new changes from? And the user credentials given on conf file, are those required for pulling in the new changes?

**Comment by VijayKrishn** [comment]
Kiran

Can you please share the configuration that you are using. My codebrag is
not syncing up with the new changes. Its only showing me the changes up to
the time I cloned the repo inside my repos folder.

Thank you

**Comment by gmkumar2005** [comment]
I use CentOS Linux release 7.4.1708 (Core) , git 1.8.3.1 , jdk version "1.8.0_161" ,svn, version 1.7.14

**Comment by VijayKrishn** [comment]
Hi Kiran

I was able to make it work. I have a doubt. Once I comment on a checkin, it
goes as follow up to the person. What if the other person wants to address
the comments by modifying the code and does a new check in? How can we keep
track of related check ins? Is there a way to know that the new checkin is
to address the previous follow up?

**Comment by gmkumar2005** [comment]
No none that I am aware
