### ISSUE TITLE
wget 404

### ISSUE THREAD

**Issue by jdzms23** [softwaremill/codebrag#92]
wget http://codebrag.com/latest/codebrag.zip 404 
![image](https://cloud.githubusercontent.com/assets/7744092/20996719/9397dfe2-bd3a-11e6-9994-81c9ca6cbc95.png)

**Comment by acdcjunior** [comment]
From the page source, I think the link is https://s3-eu-west-1.amazonaws.com/codebrag-dist/latest/codebrag.zip

**Comment by adamw** [comment]
Fixed, sorry for the problems :)
